"""
常量定义
"""
URL="https://kyfw.12306.cn/otn/leftTicket/query?"
T_DATE="leftTicketDTO.train_date="
F_STATION="&leftTicketDTO.from_station="
T_STATION="&leftTicketDTO.to_station="
AUTH="&purpose_codes=ADULT"
seat_info=['发出时间','到达时间','总共耗时','车次','商务座','一等座','二等座','软卧','硬卧','硬座','无座']
